### PANES ###
[panes.nav]
show_preview = 60
lock_prompt = false

# ignore_patterns = [ ".DS_Store" ]
# default_visibility = { hidden = true }

[panes.find]
show_preview = 60
lock_prompt = true

[panes.search]
lock_prompt = true
show_preview = 20
preview_layout_index = 1

one_line = true
default_sort = "none"

rg_status_template = '''
{blue:filter: {}} \s\m/\t
'''
fs_status_template = '''
{red:query: {}} \s\m/\t
'''

[panes.app]
preview_layout_index = 3
show_preview = true

### SETTINGS ###

[fd]
dot_query_show_hidden = "Always"

[rg]
empty_pattern = "-v ^ *$"

[notify]

[misc]

[history]
refind = "Search"

### MISC ###

[interface]
# hide the preview when in the query bar
hide_preview_when_cursor_disabled = true
# allow_trash_db_items = true

# prompt prefix when in the query bar: https://squirreljetpack.github.io/fist-docs/16-output-templates#the-format-template
# cwd_prompt = '{2:2} '
