[panes.nav]
    show_preview       = true
    default_visibility = { hidden = true }

[panes.find]
    on_leave_unset_dirs_only = true

[history]
    refind = "Search"

[misc]
    append_mode_logging = true
