[tui]
percentage = 50
min = 10
max = 25


[[preview.layout]]
    side       = "right"
    percentage = 40
    min        = 30
    max        = 120

[[preview.layout]]
    side       = "top"
    percentage = 50
    min        = 5
    max        = 50

[preview]
wrap = true
