#!/usr/bin/env sh
have() {
  command -v "$1" >/dev/null 2>&1
}

if have exiftool; then
    exiftool -exclude Content "$1" | tail -n +4
elif have file; then
    file -bL "$1"
else
    echo "No viewer for $1"
fi