#!/bin/zsh

# Configured by environment variables, including LESS=
# bat colorization is not idempotent, so it's important that --paging=never is a default option for bat when this is set as PAGER

set -o pipefail

have() {
  command -v "$1" >/dev/null 2>&1
}

# override/fallback
if [[ -n "$FS_PAGER" && "${${(z)FS_PAGER}[1]}:t" != "$0:t" ]]; then
    ${(z)FS_PAGER} "$@"
    exit
elif ! have bat; then
    if have lessfilter; then
        [[ -n $PG_LESS ]] && LESS+=" $PG_LESS"
        lessfilter $1
    else
        cat $1
    fi
    exit
fi

opts=()
less_opts=()
[[ -n $PG_LANG ]] && opts+=(-l $PG_LANG)
[[ -n $PG_DEFAULT ]] || opts+=(--color=always --style=changes)
[[ -n $PG_FLAGS ]] && opts+=(${(@Q)${(z)PG_FLAGS}})
[[ $HIGHLIGHT_LINE =~ ^[0-9]+$ ]] && opts+=(--highlight-line $HIGHLIGHT_LINE)
# [[ $SCROLL_LINE =~ ^[0-9]+$ ]] && less_opts+=(+$SCROLL_LINE) # Uncomment this to listen for scroll offsets from the previewer



[[ -n $PG_LESS ]] && LESS+=" $PG_LESS"
opts+=($@)

bat -p $opts | {
	IFS= read -r line
    if [ $? -eq 0 ] || [[ -n "$line" ]]; then
        echo $line
        if [[ $PG_FORCE_TTY == true ]]; then
            LESSUTFCHARDEF=E000-F8FF:p,F0000-FFFFD:p,100000-10FFFD:p less -R $less_opts > /dev/tty
        else
            LESSUTFCHARDEF=E000-F8FF:p,F0000-FFFFD:p,100000-10FFFD:p less -R $less_opts
        fi
    fi
}

