use cba::{_dbg, bo::load_type_or_default};
use matchmaker::{
    binds::{BindMap, BindMapExt, ResolvedBindMap},
    collections::HiddenColumns,
    config::{
        DisplayConfig, HelpDisplayConfig, OverlayConfig, Percentage, PreviewSetting, RenderConfig,
        RowConnectionStyle, TerminalConfig, TerminalLayoutSettings,
    },
    nucleo::nucleo,
};
use matchmaker_partial::Apply;
use ratatui::style::Modifier;
use std::path::Path;

use super::{FsAction, binds::default_binds};

#[cfg(feature = "mm_overrides")]
use crate::cli::env::get_mm_partial;

use crate::{
    config::Config,
    lessfilter::Preset,
    ui::{
        confirm_overlay::ConfirmConfig, menu_overlay::MenuConfig, options_overlay::OptionsConfig,
        prompt_overlay::PromptConfig, queue_overlay::QueueConfig,
    },
};
use fist_types::When;

// ------- MM config --------

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MMConfig {
    // configure the ui
    #[serde(default, flatten)]
    pub render: RenderConfig,

    // binds
    #[serde(default)]
    pub binds: BindMap<FsAction>,

    #[serde(default)]
    pub tui: TerminalConfig,

    // --- overlays ---
    /// Base overlay style
    #[serde(default)]
    pub overlay: OverlayConfig,

    /// Queue overlay
    #[serde(default)]
    pub queue: QueueConfig,
    /// App overlay
    #[serde(default)]
    pub app: QueueConfig,
    /// Options overlay
    #[serde(default)]
    pub options: OptionsConfig,
    #[serde(default)]
    pub prompt: PromptConfig,
    #[serde(default)]
    pub menu: MenuConfig,
    #[serde(default)]
    pub confirm: ConfirmConfig,

    // --- other ---
    #[serde(default)]
    pub help: HelpDisplayConfig,
}

impl Default for MMConfig {
    fn default() -> Self {
        // mac.mm.toml is generated by build.rs: mm.toml plus the mac-specific
        // binds (ctrl-h/cmd-backspace -> Trash, alt-backspace -> DeleteWord).
        #[cfg(target_os = "macos")]
        let src = include_str!("../../assets/config/mac.mm.toml");
        #[cfg(not(target_os = "macos"))]
        let src = include_str!("../../assets/config/mm.toml");
        toml::from_str(src).unwrap()
    }
}

pub const MATCHER_CONFIG: nucleo::Config = const { nucleo::Config::DEFAULT.match_paths() };

// -------------------------------------------------------------------------------------------

pub fn get_mm_binds(path: &Path) -> (ResolvedBindMap<FsAction>, HelpDisplayConfig) {
    let mut mm_cfg: MMConfig = load_type_or_default(path, |s| toml::from_str(s));
    #[cfg(feature = "mm_overrides")]
    if let Some(partial) = get_mm_partial() {
        mm_cfg.render.apply(partial);
    }

    mm_cfg.binds.extend_from(default_binds());

    (mm_cfg.binds.resolve_semantics(&[]), mm_cfg.help)
}

pub fn get_mm_cfg(
    path: &Path,
    cfg: &Config,
) -> MMConfig {
    let mut mm_cfg: MMConfig = load_type_or_default(path, |s| toml::from_str(s));
    #[cfg(feature = "mm_overrides")]
    if let Some(partial) = get_mm_partial() {
        mm_cfg.render.apply(partial);
    }

    mm_cfg.binds.extend_from(default_binds());

    // Render display
    let RenderConfig {
        ui: _,
        query: _,
        results,
        status,
        preview,
        footer,
        header: _,
    } = &mut mm_cfg.render;

    // disable some configuration settings for consistency
    results.multi_prefix = results.multi_prefix.chars().next().unwrap_or('▌').into(); // single width
    results.right_align_last = true;
    results.stacked_columns = false;
    results.separator = Default::default();
    results.min_width = results.min_width.max(10);
    results.autoscroll.initial_preserved = 2;
    // loc column hidden by default (rg panes only)
    results.hidden_columns = HiddenColumns::from_iter([2]);

    if cfg.global.mm.reverse.is_some() {
        results.reverse = cfg.global.mm.reverse
    }

    if status.template.is_empty() {
        status.template = r#"\m/\t"#.to_string();
    }

    *footer = DisplayConfig {
        style: Default::default(),
        wrap: true,
        row_connection: RowConnectionStyle::Full,
        ..Default::default()
    };

    // Preview display

    preview.initial.index = None;
    preview.initial.percentage = Percentage::new(70);

    let command = Preset::Preview.to_command_string(When::Auto);
    if preview.layout.is_empty() {
        preview.layout = vec![PreviewSetting {
            command,
            ..Default::default()
        }]
    } else if preview.layout[0].command.is_empty() {
        preview.layout[0].command = command
    }

    let tui = &mut mm_cfg.tui;
    // non-fullscreen by default
    if cfg.global.mm.fullscreen {
        tui.layout = None
    } else if tui.layout.is_none() {
        tui.layout = Some(TerminalLayoutSettings {
            percentage: Percentage::new(60),
            ..Default::default()
        })
    }
    #[cfg(debug_assertions)]
    {
        tui.clear_on_exit = false;
    }

    if let Err(p) = mm_cfg.options.base.border {
        let mut full = mm_cfg.overlay.border.clone();
        full.apply(p);
        mm_cfg.options.base.border = Ok(full)
    }
    if let Err(p) = mm_cfg.menu.border {
        let mut full = mm_cfg.overlay.border.clone();
        full.apply(p);
        mm_cfg.menu.border = Ok(full)
    }
    if let Err(p) = mm_cfg.queue.border {
        let mut full = mm_cfg.overlay.border.clone();
        full.apply(p);
        mm_cfg.queue.border = Ok(full)
    }
    if let Err(p) = mm_cfg.app.border {
        let mut full = mm_cfg.overlay.border.clone();
        full.apply(p);
        mm_cfg.app.border = Ok(full)
    }
    if let Err(p) = mm_cfg.confirm.border {
        let mut full = mm_cfg.overlay.border.clone();
        if p.modifier.is_none() {
            full.modifier = Modifier::ITALIC
        }
        full.apply(p);
        mm_cfg.confirm.border = Ok(full)
    }

    _dbg!(&mm_cfg);
    log::debug!("Final: {mm_cfg:?}");

    mm_cfg
}
