[package]
name = "fist-size"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true
description = "Data structure for computing file size trees"

[dependencies]
crossbeam-channel = "0.5"
dashmap = "5.5"
rayon = "1.8"

[dev-dependencies]
tempfile = "3.8"
